### ISSUE TITLE
Home Page- Create Poll Form

### ISSUE THREAD

**Issue by rosenbergmichael** [chingu-voyages/v30-geckos-team-08#33]
-3 input text fields (question and 2 options)
-Button for Add Option text field
-Button for Create Poll
-Link/Button for pop up to prevent duplicates, options for IP and cookie, explanation of benefits

**Comment by shepherdlewis000** [comment]
NOTES ON  Preventing "double voting" - wording is below
-----------------------------------------

Prevent "double voting"
To prevent visitors from voting more than once, the following strategies may be used (choose one if desired):

Cookie check
IP Address check
Both (most secure)

-----------------------------
Explanatory text (when clicking question mark, popup modal or hover text)

 
Cookie check: A cookie will be set in the visitor's browser when they vote and no further votes will be allowed on this poll once the cookie is set.
NOTE: A determined "cheater" can always clear his or her browser cookies or use a different browser to vote more than once.


IP Address check: A visitor's IP address will be recorded and no further votes on this poll will be allowed from that address.
NOTE: Because some environments share a single IP address, e.g. some corporations, schools, & hospitals, this option is not ideal if distributing your survey to multiple recipients in an organization that might be sharing an IP.

Both: Cookie check AND IP Address check will both be performed.

**Comment by shepherdlewis000** [comment]
Cool transition effect for placeholder text transition to input label

Article on this particular effect: https://knowbility.org/blog/2019/animating-form-labels
Codepen from article: https://codepen.io/team/Knowbility/pen/agwJjO

Here's a more stylized usage of that effect:  https://codepen.io/arcs/pen/OmZaex

NOTE If we did something like this second example (a guided stepwise form entry of the poll question & answers, we COULD have it ask first 1) what is your polls question then ask for choice/answer 1, then choice/answer 2, then have a yes/no choice that asks "Do you want to add another choice/answer?"
